### ISSUE TITLE
MobX strict mode

### ISSUE THREAD

**Issue by binchik** [pinqy520/mobx-persist#1]
Hello, thanks for your awesome work!

Is there a way to make mobx-persist work with mobx strict mode? When I have it turned on, I get `Possible Unhandled Promise Rejection` warnings, and the stores are not persisted.

If you guide me I can help with a PR on that, since I really want to use the strict mode. The mobx `action` uses `extras.allowStateChanges` function under the hood, I think it can be used to ignore the mobx strict mode.

**Comment by binchik** [comment]
I just did it wrapping store updating code into `extras.allowStateChanges`.

**Comment by pinqy520** [comment]
@binchik 

i have fixed it by wrapping the init function into a `action`, and released a new version.

thanks for your reporting!
