### ISSUE TITLE
Post-hydration callback?

### ISSUE THREAD

**Issue by zolrath** [pinqy520/mobx-persist#10]
Hi!
I'm currently setting a randomly generated userId upon creation of my UserStore.

I would like to @persist this userId and only have it be generated if the variable is empty in the store.
If I set this creation in the constructor of my store it is run every time, only to then be replaced by the  persisted id.

I'd rather skip regenerating this Id if I already have done so and persisted it.

Is there a `persistLoaded` callback or something that gets called on my store after persist is complete that I can use to perform validations post-hydration?

**Comment by yogurt1** [comment]
You can use `serializable` decorator from *serializr* package instead of `persist` decorator

**Comment by pinqy520** [comment]
Hi, thanks for report~! @zolrath 

I have changed the `persistStore` function to `hydrate`, and it returns a `Promise`.

``` javascript
import { create } from 'mobx-persist'

const hydrate = create({})

const appState = new AppState
hydrate('appState', appState, (window as any).__INITIAL_STATE__.app)
  .then(() => console.log('appState hydrated'))
```

I have published this feature to an incompatible version (0.3.0), and updated the readme.
