### ISSUE TITLE
How works with multiple stores?

### ISSUE THREAD

**Issue by hasaezs** [pinqy520/mobx-persist#11]
Hi! I'm trying to set up multiple stores, but it does not work. I leave the code I'm working with.

```javascript
import { create } from 'mobx-persist';
import { AsyncStorage } from 'react-native';

import AppStore from './appStore';
import AuthStore from './authStore';
import LocalesStore from './localesStore';

const persistStore = create({ storage: AsyncStorage });

const store = {
  app: new AppStore(),
  auth: new AuthStore(),
  locales: new LocalesStore()
};

export default persistStore('store', store);
```
Neither works this way
```javascript
const store = {
  app: persistStore('app', new AppStore()),
  auth: persistStore('auth', new AuthStore()),
  locales: persistStore('locales', new LocalesStore())
};
```

Any examples for this to work? Thanks in advance.

**Comment by pinqy520** [comment]
0.3.0 or 0.2.0？

**Comment by pinqy520** [comment]
0.3.0

``` javascript
const hydrate = create()
const store = {
    app: new AppStore(),
    auth: new AuthStore(),
    ...
}
hydrate('app', store.app)
hydrate('auth', store.auth)
...
```

**Comment by pinqy520** [comment]
https://github.com/pinqy520/mobx-persist/blob/master/dev/index.tsx#L9-L15

**Comment by hasaezs** [comment]
Same error that before, just that the app works, but it is not clear to me if mobx-persist is working.

![Error](http://i.imgur.com/eROz8kg.jpg)

Any suggestions?

**Comment by hasaezs** [comment]
Add: Only happens when I add mobx-persist.

**Comment by pinqy520** [comment]
Which version? mobx@^3.0.0 + mobx-persist@^0.3.0?

I just try and it works.

Did you use `@persist` decorator in your store?

and here is a `react-native` project example.

https://github.com/pinqy520/mobx-persist/tree/master/examples/rn

or can you provide more information of your project?

**Comment by hasaezs** [comment]
> mobx@^3.1.0
> mobx-persist@^0.3.0
> mobx-react@^4.1.0

I leave a gist with the files I'm using in my project.

https://gist.github.com/hasaezs/e5094c153989dac2c9171e3aa6216edf

**Comment by pinqy520** [comment]
https://gist.github.com/hasaezs/e5094c153989dac2c9171e3aa6216edf#file-authstore-js-L8

**Comment by pinqy520** [comment]
https://gist.github.com/hasaezs/e5094c153989dac2c9171e3aa6216edf#file-authstore-js-L8

`user` is an object, you should use `@persist('object')`
