### ISSUE TITLE
it dosent work on RN

### ISSUE THREAD

**Issue by matthewfang** [pinqy520/mobx-persist#13]
I write the same code for RN, but it dosent work, I cant find any state under window__STATE__, how can I  initail the state that I have persisted

**Comment by yogurt1** [comment]
Try this:
```
class Root extends React.Component {
  state = { persistedState: null }
 
  componenetWillMount() {
    AsyncStorage.getItem('persistedState').then(persistedState => this.setState({ persistedState }))
  } 

  render() {
    const { persistedState } = this.state
    return persistedState === null ? <Loader /> : <App persistedState={persistedState} />
  }
}
```
Show loader when loading state from AsyncStorage. And after load, rehydrate stores with preloaded state and render entire App

**Comment by pinqy520** [comment]
The `initialState` is just for server side render of `react-dom`. see the example for rn: https://github.com/pinqy520/mobx-persist/tree/master/examples/rn
