### ISSUE TITLE
Problem with React Native 

### ISSUE THREAD

**Issue by kanzitelli** [pinqy520/mobx-persist#15]
Hello, thanks a lot for your library 🙌
I'm developing app with RN + MobX (+ your persist library) and have faced a problem when I wanted to create `@persist('map', SomeItem)` with Models.User which I defined as in your example in README. Everything seemed to be working good but I was getting an error when I tried to hydrate my multiple stores. After some research, I have solved it by changing `@persist('map', SomeItem)    @observable m = asMap<SomeItem>({})` to `@persist('map', Models.User) @observable users = observable.map({});`. I will put some code here if someone has the same problem in future. 

_stores/index.js_:
```
import { create } from 'mobx-persist';
import { AsyncStorage } from 'react-native';

import Account from './Account';
import Profiles from './Profiles';

const hydrate = create({ storage: AsyncStorage });

const store = {
  Account,
  Profiles,
}

hydrate('Account', store.Account);
hydrate('Profiles', store.Profiles);

export default {
  Account,
  Profiles,
};
```

_stores/Profiles.js_:
```
import { observable, action, computed } from 'mobx';
import { persist } from 'mobx-persist';

import Models from '../Models/index';

class Store {
  @persist('map', Models.User) @observable users = observable.map({});

  // some methods and props...

}

export default new Store();

```

_Models/User.js_:
```
import { observable } from 'mobx';
import { persist } from 'mobx-persist';

class User {
  @persist @observable id = 0
  @persist @observable first_name = ''
  @persist @observable last_name = ''

  // more properties
}

export default User;
```

This code works for me in RN. Maybe you could add this example to the README, I think it would be helpful for others.

**Comment by pinqy520** [comment]
![image](https://cloud.githubusercontent.com/assets/5719833/24275824/43ee3550-106d-11e7-8824-d53ea0a581c4.png)

This error ? 

OK, I will update the README.

Thank you for report !

**Comment by kanzitelli** [comment]
@pinqy520, thank you for the reply. No, I was getting the following error:
![simulator screen shot mar 23 2017 9 13 21 pm](https://cloud.githubusercontent.com/assets/4402166/24276551/ea55bc7a-100d-11e7-9fd0-6c4452df714c.png)
