### ISSUE TITLE
Latest change to state is not persisted

### ISSUE THREAD

**Issue by onselakin** [pinqy520/mobx-persist#19]
This is a definition inside my store:

`@persist('list') @observable formationMatrix: Array<Array<Player>> = []`

This is how I add an object to the formationMatrix:

`appState.formationMatrix[player.position][this.targetPositionOrder] = player`

Note that both of the arrays are initialized before use.

The latest assignment is not persisted to AsyncStorage. Any directions to ease debugging the issue?

Thank you.

**Comment by pinqy520** [comment]
@onselakin Hi, I just test nested array [here](https://github.com/pinqy520/mobx-persist/blob/master/dev/app.tsx#L25), and it works fine. If you want to debugging mobx states or AsyncStorage, you can try: [mobx-remotedev](https://github.com/zalmoxisus/mobx-remotedev) or [reactotron](https://github.com/infinitered/reactotron).
