### ISSUE TITLE
Ability to react to persisted stores being loaded

### ISSUE THREAD

**Issue by antoligy** [pinqy520/mobx-persist#2]
Hey,

I'm not quite sure if this already possible, so please let me know if I'm wrong.  I have a use-case where I have dependent components that I would like to render based on computed values; computed values which are populated by persisted observables.

When I load up the store, at first the observables are unset and so the computed value returns a different value to what it would after the store's persisted state has been loaded.  Unfortunately in my component lifecycle I'm not given the ability to react to the computed value.

How would you recommend I solve this use-case?  (For the meantime I have dummy calls to the observable values which triggers a `componentWillReact`, however this is not-desirable!)

**Comment by pinqy520** [comment]
Hi, @antoligy 

I am not sure if I understand your issue correctly. Is this the case?

``` javascript
class SomeStore {
	@persist @observable b
	@computed get a() {
		return this.b
	}
}
// persisted state:
// { "b": 1 }
```

It will react, as long as you declare `b` in the store.

If it is not the case, can you provide some examples.

Thanks.

**Comment by antoligy** [comment]
Hey,

My use-case is one where I do this in my component:
```javascript
  componentDidMount() {
    if (this.props.auth.isLoggedIn) {
      this.doneLoadingAuth();
    }
  }

  componentWillReact() {
    this.doneLoadingAuth();
  }
```

and in my store
```javascript
  @persist @observable token;

  @computed get user() {
      return (this.token) ? jwt.decode(this.token, '', true) : false;
  }

  @computed get isLoggedIn() {
    return (!this.token === undefined || !!this.user)  
  }
```

I can trigger `componentWillReact`/`componentWillUpdate` when the value is loaded by adding a call to `this.props.auth.token` to the render method of my component, but this seems non-ideal as I'm surfacing logic that I really shouldn't be using.

**Comment by pinqy520** [comment]
Hi, @antoligy 

In `mobx-react`, a component only refreshes when the observable, used in its render function, is changed, and it will trigger the `componentWillReact` function. If you just want to call `this.doneLoadingAuth()`, you should use `autorun`, `reactive`, or `when`, instead of putting it to the lifecycle of the component.

``` javascript
// componentDidMount
this.r = reactive(
  () => this.props.auth.isLoggedIn
  () => this.doneLoadingAuth()
)

// componentWillUnmount
this.r() // dispose the autorun
// or outside of the component
```

**Comment by antoligy** [comment]
Sorry, saw this and totally forgot to reply.  This helped and I was able to get it to work, thanks very much!
😄
