### ISSUE TITLE
Not working when changing object

### ISSUE THREAD

**Issue by dnish** [pinqy520/mobx-persist#20]
Hey,
in the first version of our app, we have an object like this defined:

    @persist('object') @observable notifications = {
        seenTutorial: false,
    };

In a newer version, we have to add a new value to it, f.e.:

    @persist('object') @observable notifications = {
        seenTutorial: false,
        seenFolderChoose: false
    };

If we know modify <code>seenFolderChose</code> to true, the change won't be saved to the disk and there is also no "re-render" when changing the value (most of the time, sometimes we got one).

**Comment by dnish** [comment]
I can make it "work" if I use a modifier and overwrite the whole object:

    @action.bound setSeenFolderChoose() {
       const obj = Object.assign({seenFolderChoose:true},this.notifications);
        this.notifications = obj; 
    }

But I guess the other way would be probably better.

**Comment by pinqy520** [comment]
``` javascript
@persist('object') @observable notifications = {
    seenTutorial: false,
};
```

to

``` javascript
class Notifications {
    @persist seenTutorial = false
}
@persist('object', Notifications) @observable notifications = new Notifications
```

to 

``` javascript
class Notifications {
    @persist seenTutorial = false
    @persist seenFolderChoose = false
}
@persist('object', Notifications) @observable notifications = new Notifications
```

**Comment by dnish** [comment]
Hey,
now I'm using this:

```
class Notification {
    @persist @observable seenTutorial = false;
    @persist @observable seenFolderChoose = false;
}
```

```
 @persist('object', Notification) @observable notifications = new Notification();
```

The value is now changing, but it isn't saved after restart.
