### ISSUE TITLE
How to persist structured objects

### ISSUE THREAD

**Issue by albertored** [pinqy520/mobx-persist#23]
I have an observable `range` object that I want to persist. It is defined as follow:

```javascript
range = {
    start: moment(),
    end: moment()
}
```

where `start` and `end` are [moment.js](https://momentjs.com/) objects.

With plain serializr I would do something like

```javascript
const rangeSerializer = ({start, end}) => {
	return {start: start.unix(), end: end.unix()}
}

const rangeDeserializer = ({start, end}) => {
	return {start: moment.unix(start), end: moment.unix(end)}
}

class Store {
    @serializable(custom(rangeSerializer, rangeDeserializer)) @observable range = {}
}
```

but using `@persist(custom(rangeSerializer, rangeDeserializer)) @observable range = {}` does not work. I get no erros but data are never written to `localStorage`. When instead I remove that `persist` the other persisted data contained in `Store` are correctly written to `localStorage`.

**Comment by pinqy520** [comment]
Just use `@serializable(custom(rangeSerializer, rangeDeserializer))` instead of `@persist`

``` javascript
class Store {
    @serializable(custom(rangeSerializer, rangeDeserializer)) @observable range = {}
}
hydrate('store', Store)
```

**Comment by albertored** [comment]
Thanks.

I found also another solution that preserves the `persist` decorator.

```javascript
const momentSerializer = (m) => m.unix()
const momentDeserializer = (m) => moment.unix(m)
const rangeSchema = createSimpleSchema({
	start: custom(momentSerializer, momentDeserializer),
	end: custom(momentSerializer, momentDeserializer)
})

class Store {
    @persist('object', rangeSchema) @observable range = {}
}
```
