### ISSUE TITLE
Data only persists first restart

### ISSUE THREAD

**Issue by itswaze** [pinqy520/mobx-persist#24]
Hi!
Im pretty new to MobX so im struggling a bit.
On my store I persist the data this way:

```
import { observable, action } from 'mobx'
import { persist } from 'mobx-persist'

class Store {
  @persist('list') @observable eventos = []

  @action addEvento (id, title) {
    this.eventos.push({
      id: id,
      nome: title
    })
  }
}

export default new Store();
```

then, on my component I have this:
(not sure if this part is right...)

```
const hydrate = create({ storage: AsyncStorage })
hydrate('list', Store)
```

Everytime I add an item to my list, it runs this: `this.props.store.addEvento(id, title)`
The item show correctly, and when I try to restart the first time, it's still there, but on the second time it disappears.

A little video showing the problem:
https://vid.me/nnmqr

**Comment by pinqy520** [comment]
@itswaze I just want to reproduce your issue [here](https://github.com/pinqy520/mobx-persist/blob/master/examples/rn/src/store.js#L25-L30), and It works fine after I reload several times. Maybe I need more information like what's the different between your code and [the example](https://github.com/pinqy520/mobx-persist/tree/master/examples/rn)

**Comment by itswaze** [comment]
@pinqy520 well, I don't seem to find any difference...

The code I posted for the store is the full code. And for my component, I only added 
```
const hydrate = create({ storage: AsyncStorage })
hydrate('list', Store)
```

**Comment by itswaze** [comment]
@pinqy520  I couldn't find the problem, so I started the app from scratch and I was adding the components one by one, xcode definitions, etc.
I've found out, that `Allow Arbitrary Loads` on XCode is the problem... Which is really strange! 

But I need to have that so I can make http requests... Do you have any idea why this happens?

**Comment by pinqy520** [comment]
Are there some data, requested from server, will overwrite the list?

**Comment by itswaze** [comment]
Nothing...
I've tried disabling everything that requests data from the server, and I still get the error.
Only removing the `Allow Arbitrary Loads` makes it work... But I really can't remove it :s

**Comment by pinqy520** [comment]
Do you try [`mobx-logger`](https://github.com/winterbe/mobx-logger), [`mobx-remotedev`](https://github.com/zalmoxisus/mobx-remotedev/) or any mobx debug tools to trace the data change?

**Comment by itswaze** [comment]
I didn't, never used them before. When I try to use `remotedev` I get `cannot read map of undefined`.

**Comment by pinqy520** [comment]
@itswaze Hi, my colleague reproduced this issue and found out that is a serializr issue. I will publish a new version to avoid this issue.

**Comment by pinqy520** [comment]
Fixed in 0.3.4, and if 0.3.4 still reproduce the issue, feel free to reopen it.

**Comment by itswaze** [comment]
Still not persisting, only on first restart. Don't really know what else I can do.

**Comment by pinqy520** [comment]
what's the version of serializr in your project

**Comment by itswaze** [comment]
It's version `1.1.12`

**Comment by itswaze** [comment]
@pinqy520 here is a stripped down version of my app: https://github.com/itswaze/PersistTest
So you can test if you want. If you try to remove `App Transport Security Settings`, more specifically the `Exception Domains` from xcode you will see that the app will persist the data.

**Comment by pinqy520** [comment]
@itswaze ok, I will test tomorrow.

**Comment by itswaze** [comment]
@pinqy520 did you have a chance to test it? :)

**Comment by pinqy520** [comment]
@itswaze The project cannot be built successfully after I `npm install`. i opened an issue https://github.com/itswaze/PersistTest/issues/1 .

**Comment by itswaze** [comment]
@pinqy520 hey! I had to create a new project, It had alot of issues the other one. And this one is smaller. Here you go (same link): https://github.com/itswaze/PersistTest

**Comment by pinqy520** [comment]
![image](https://user-images.githubusercontent.com/5719833/29370297-88a06006-82d7-11e7-842b-caf4a285d040.png)

It seems that you forgot to put these fonts into a relative path

**Comment by itswaze** [comment]
Sorry :p added

**Comment by pinqy520** [comment]
https://github.com/itswaze/PersistTest/blob/master/app/Store.js#L8

**Comment by itswaze** [comment]
Already tried that, still not working. It's set to test because I was testing some things, but It was list before. Also tried `object`

**Comment by itswaze** [comment]
I tried again the project I made for you to try, and I found out that list was working. So I searched for anything that may be confliting with it. And I found out that I already had a local storage called `list`, on another screen! I think that was it :)

For now it's working! Thank you so much for helping me! Keep up the good work 👍

**Comment by blackstar217** [comment]
I had also that issue.
So, in that case, How can I solve that problem?

Here is my codebase
in A store
@persist('list') @observable a  = []

in B store
@persist('list) @observable b = []

How can I persist both observable values for the list?
