### ISSUE TITLE
Reaction[Reaction@21] Error: [serializr] Failed to find default schema for [object Object]

### ISSUE THREAD

**Issue by dnish** [pinqy520/mobx-persist#26]
Hey,
when I try to call hydrate, I get the following error:

     ExceptionsManager.js:71 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@21] Error: [serializr] Failed to find default schema for [object Object]

Any idea what could cause this? If I remove hydrate, everything is working fine again.

It even happens if I create a new store:

```
class Test {
    @observable test = true;

    constructor() {

    }
}

const testStore = new Test();


hydrate('test',testStore).then(() => {


});
```

**Comment by dnish** [comment]
I guess the issue was that the store didn't have any persistent value. After adding one, the error has disappeared.

**Comment by daemir** [comment]
What do you mean by persistent value? I'm getting the same error

**Comment by dnish** [comment]
You need at least one value with @persistent in your store, f.e

   @persistent @observable test = 1;

**Comment by ccfiel** [comment]
I got this problem also even I have this code
` @persist @observable test = 1;`
 any other solution?

**Comment by mabualwafa** [comment]
me too still facing the same issue.
