### ISSUE TITLE
Fails when using a subclassed Store

### ISSUE THREAD

**Issue by consense** [pinqy520/mobx-persist#32]
I am using some shared methods across stores so inherit from a ParentStore class. In this case mobx-persist (or rather serializr) doesnt seem able to deduct the schema correctly.
Minimally adjusted test case from the readme:

```
import { observable } from 'mobx';
import { create, persist } from 'mobx-persist';


class ParentStore {
}


class SomeStore extends ParentStore {
	@persist('object') @observable         obj = { a: 1, b: 2 };
}

export const someStore = new SomeStore();

const hydrate = create({ jsonify: true });
hydrate('some', someStore, {
	obj: { a: 2, b: 1 } // initial state
}).then(() => console.log('some hydrated')); // post hydration
```

this gives ``mobx.module.js?eae6:3100 [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@2] Error: [serializr] Failed to find default schema for [object Object]`` which is thrown from serializr

**Comment by pinqy520** [comment]
@consense Thanks for your report, fixed in v0.4.1~

**Comment by consense** [comment]
@pinqy520 amazing - thanks for looking into this so swiftly - works like a charm!

**Comment by zerbinidamata** [comment]
Has this fix been released? 

I'm running into the same issue.
