### ISSUE TITLE
How to use with mst ?

### ISSUE THREAD

**Issue by lecler-i** [pinqy520/mobx-persist#33]
Hello,

Is it possible to use `mobx-persist` with `mobx-state-tree` ?
If so, can you give an example ? 

Thanks you

**Comment by pinqy520** [comment]
Hi, `mobx-state-tree` can easily persist store to local storage without any lib. https://github.com/mobxjs/mobx-state-tree/blob/master/packages/mst-example-bookshop/src/stores/CartStore.js#L89-L90

**Comment by yordis** [comment]
@pinqy520 hey mate I commented on #37

**Comment by agilgur5** [comment]
Since it might not be clear to check #37 from this issue, just wanted to note here that per https://github.com/pinqy520/mobx-persist/issues/37#issuecomment-493830440 I've created a separate library for to handle MST called [mst-persist](https://github.com/agilgur5/mst-persist) :)
