### ISSUE TITLE
Question - detect when local storage changed

### ISSUE THREAD

**Issue by sagivo** [pinqy520/mobx-persist#34]
The library assumes a one-way direction for updating local storage. The only time the store updated from local storage is on initial load. is there a way to detect that local storage updated and automatically load the new values from there?

to clarify - assume some code updates localstorage outside of the store, i need a way to send an event to the store asking to reload changes from localstorage.

**Comment by pinqy520** [comment]
``` javascript
const result = hydrate('some', someStore, initialState)
const rehydrate = result.rehydrate
result.then(() => console.log('some hydrated'))

window.addEventListener("storage", rehydrate)
```

**Comment by sagivo** [comment]
@pinqy520 perfect, thank you.
