### ISSUE TITLE
Q on state rehydrate 

### ISSUE THREAD

**Issue by Anoupz** [pinqy520/mobx-persist#38]
Need some help with my use case.
Using persist I hydrate the org details in local-storage and and rehydrate them. From componentDidMount I make an asyncAction call using the org details. When I refresh first the page org details are empty. ComponentDidMount gets called first before rehydration hence the api calls didn’t make through. How could I over come this? Is there any best practice on when to re hydrate the state on page refresh?

**Comment by pinqy520** [comment]
``` javascript
async componentDidMount() {
  await hydrate('org', orgDetails)
  autorunAsync(() => {...})
}
```
