### ISSUE TITLE
Migrating persisted variable from type A to type B

### ISSUE THREAD

**Issue by jorgenbs** [pinqy520/mobx-persist#39]
Say I have a 
```
@observable
@persist('list')
activities = [];
```
That we need to change to
```
@observable
@persist('map')
activities = new Map();
```

At the moment this change fails for users who are updating the app, since they are trying to hydrate the existing store with `activities` as a `list`.

I'm wondering whats the suggested way of handling these types of migrations?

**Comment by pinqy520** [comment]
rename?

**Comment by jorgenbs** [comment]
Wow, duh. Thats a good and simple answer.
