### ISSUE TITLE
More documentation please 

### ISSUE THREAD

**Issue by michaelsync** [pinqy520/mobx-persist#41]
Hi,

This repo looks promising but it would be nice if we have more documentation or more sample. 

I am looking at this sample https://github.com/pinqy520/mobx-persist/tree/master/examples/rn/src but I don't see how rehydration works. 

What are we supposed to do in in those hydrated methods? 

```console.log('some hydrated')```
 

What I am trying to is to save the data in local storage or session storage and get the data back on page refresh. 

I created this sample to show you what I am trying to do. https://github.com/michaelsync/js-lab/tree/master/mobx-persist-sample . 

You can use the following command to run the sample. 

- yarn install
- yarn start 

It has two components called "entry" page and "result". User can enter something in "entry" page and show that data in the "result" page.  There is one store called userDataStore that has only one property called data. 

When you click on "Click Me" in the entry page, the data that you typed on text box will be saved in user data store. and it retrieves the data back from the result page. 

The steps to replicate the issue. 

1. run the program by using ```yarn start```
2. enter something in textbox and click on "Click me" (It will redirect to the result page)
3. you will see what you entered in the result page. 
4. Refresh the page (press F5) - the data will be lost. 

The issue is that I don't know what to do in rehydration. I am using the provider to inject the store. 

Can you please help me with the steps that I need to do in hydration and rehydration? 

 
 **Updated**

The solution that I found is to use the sessionStorage/local storage directly from store instead of using mobx-persit. but yes. I still would like to know if there is any better way. Thanks.

**Comment by michaelsync** [comment]
@pinqy520 any idea?

**Comment by pinqy520** [comment]
https://github.com/michaelsync/js-lab/blob/master/mobx-persist-sample/src/App.tsx#L4
``` typescript
import { UserDataStore } from './stores/userDataStore';
// should be 
import { userDataStore } from './stores/userDataStore';
```

UserDataStore -> userDataStore

**Comment by michaelsync** [comment]
@pinqy520 Thanks. But it still doesn't work. The state still loses after the page refresh.

**Comment by pinqy520** [comment]
https://github.com/pinqy520/js-lab

**Comment by michaelsync** [comment]
Thanks. It works.
