### ISSUE TITLE
Encrypting data - best practice?

### ISSUE THREAD

**Issue by oriharel** [pinqy520/mobx-persist#47]
I'd like my data to be encrypted when persisted. What would you suggest as a best practice for that? suppose I'll take care of the encrypting key generation and the algorithm - where would be the best place to perform such an action in the flow? My case is in React Native.

**Comment by oriharel** [comment]
Managed using Serializr

**Comment by ararog** [comment]
@oriharel I have similar requirement, how you manage to do that?

**Comment by oriharel** [comment]
I believe @blankg can add a code snippet

**Comment by blankg** [comment]
@ararog, missed this mention but here is the code snippet anyway:
`import { createModelSchema, custom } from "serializr";`
`class User {
	@persist
	@observable
	username = "";
}`
`createModelSchema(User, {
	username: custom(encryptString, decryptString)
});`
