### ISSUE TITLE
Could there be some examples that do not use decorators?

### ISSUE THREAD

**Issue by 0xCMP** [pinqy520/mobx-persist#5]
Not everywhere supports decorators (i.e. create-react-app or next.js) so to use MobX stores need to be setup/written without decorators.

It hasn't been immediately clear how to use `@persist` because I'm not sure what some of the types of the TypeScript code are or how the overloading plays out.

Could there be some examples written without decorators?

**Comment by pinqy520** [comment]
Thank you for report. There is no support for the situation without decorators now, but I will add the support in a few days.

**Comment by pinqy520** [comment]
Hi....it works without decorators now. here is an example: https://github.com/pinqy520/mobx-persist/blob/master/dev/non-decorator.tsx

**Comment by 0xCMP** [comment]
Thank you! I'll try it out tonight.
