### ISSUE TITLE
Example for list (array)

### ISSUE THREAD

**Issue by brankopesevski** [pinqy520/mobx-persist#6]
I am unable to get the serialization/de-serialization to work with list in react-native asyncStorage, can someone provide example how to do this? I was able to make it work with objects, maps and primitives but never with list (array).

I declare list inside a class
`@persist('list')   @observable  @serializable numList = [1,2,3,4]`

and an action to get it

`@action getNumList(){console.log(this.numList)}`

but the result from the console.log is always empty object.

Also if I do an empty list and than call the setter action to push values inside the array nothing happens and I have again empty object.

**Comment by pinqy520** [comment]
i can't understand your issue. i add some test for list, and it works well (https://github.com/pinqy520/mobx-persist/blob/master/dev/app-state.ts#L9). 

you can clone my whole repo and run to see the test.

```
git clone 
npm install 
npm start
```

can you provide more information?

**Comment by brankopesevski** [comment]
Hey, thanks for the reply.

It works well, I was expecting the list from serializr to be pretty printed with console.log as the object and map. My mistake, I am new with MobX and Serializr so if I do `console.log(this.numList.toJS())` I get all the array items as expected.

I am closing this.
